id = "linear-theme"
name = "Linear Theme"
version = "0.0.1"
schema_version = 1
authors = ["Adrian Lam <me@adrianlam.sh>"]
description = "Unofficial Linear-inspired light and dark theme for Zed."
repository = "https://github.com/adriandlam/zed-linear"
