name: Release Zed Extension

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release Zed Extension
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v2
        with:
          extension-name: linear
          push-to: adriandlam/extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
